name: uploading .war to tomcat
on:
  push:
    branches:
      - main
  workflow_dispatch:  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4


      - name: build .war file
        run: mvn clean package -DskipTests

      - name: upload .war to tomcat
        run: |
               WAR_FILE=$(ls target/*.war | head -n 1)
               APP_NAME=kalyanapplication
               curl -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} \
                 --upload-file $WAR_FILE \
                  http://${{ secrets.TOMCAT_HOST }}:8081/manager/text/deploy?path=/$APP_NAME
