name: deploying war to tomcat
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build war file
        run: mvn clean package

      - name: deploy .war to tomcat
        run: |
              WAR_FILE=$(ls target/*.war | head -n 1)
              APP_NAME=kalyanapp
              curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
                --upload-file "$WAR_FILE"\
                "http://${{ secrets.TOMCAT_HOSTNAME }}:8081/manager/text/deploy?path=/$APP_NAME&update=true" 
                
              

               
      
    
